name: Build Installer

run-name: ${{ github.event_name != 'workflow_dispatch' && (github.event.head_commit.message || format('`[PR]` {0}', github.event.pull_request.title)) || 'Manual Build' }}

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:
    name: Build Installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build for Windows
        run: dotnet publish --no-restore -r win-x64 -p:BuildNumber="${{ github.run_number }}"

      - name: Upload Artifact for Windows
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoader.Installer
          path: Output/win-x64/
        
      - name: Build for Linux
        run: dotnet publish --no-restore -r linux-x64 -p:BuildNumber="${{ github.run_number }}"

      - name: Upload Artifact for Linux
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoader.Installer.Linux
          path: Output/linux-x64/
          
      - name: Build for MacOS
        run: dotnet publish --no-restore -r osx-x64 -p:BuildNumber="${{ github.run_number }}"

      - name: Upload Artifact for MacOS
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoader.Installer.MacOS.x64
          path: Output/osx-x64/
