on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  compile_windows:
    name: Windows
    uses: ./.github/workflows/compile_windows.yml
    with:
      VERSION: ${{ inputs.VERSION }}
      
  compile_linux:
    name: Linux
    uses: ./.github/workflows/compile_linux.yml
    with:
      VERSION: ${{ inputs.VERSION }}
      
  compile_macos:
    name: MacOS
    uses: ./.github/workflows/compile_macos.yml
    with:
      VERSION: ${{ inputs.VERSION }}